name: End-to-end tests
# トリガーするイベントを設定。この場合はpush
on: [push]
jobs:
  # 任意のジョブ名を指定
  cypress-run:
    # 使用するランナーを指定。
    runs-on: ubuntu-20.04
    steps:
      # リポジトリをチェックアウトし、ワークフローがリポジトリにアクセスできるようにする
      # 参考: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Next.jsアプリを起動
      - name: Start App
        run: |
          yarn
          yarn build
          yarn start &

      # cypress-io/github-action@v4 を使用してCypressを実行
      - uses: cypress-io/github-action@v4
        with:
          # Next.js (http://localhost:3000) の起動を待つ
          wait-on: 'http://localhost:3000'
          # Cypress を ./e2e/ に配置しているため、working-directoryを指定する
          # デフォルトはルートディレクトリ
          # 参考: https://github.com/cypress-io/github-action#working-directory
          working-directory: e2e

      # Cypress実行時に生成されたビデオとスクリーンショットを保存できる
      # 参考: https://github.com/cypress-io/github-action#artifacts
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Cypress E2E Videos
          path: e2e/cypress/videos
